### ISSUE TITLE
skipping allow_models throws error saying Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ilyaskazi** [augustusnaz/laravel-vouchers#2]
Hey @augustusnaz 

I have generated 5 vouchers that were associated with Product model.
`$vouchers = $product->createVouchers(5);`

Now when I redeem any voucher by code or voucher, it throws error saying _Invalid argument supplied for foreach()_ on line #340 of file: _vendor\moirei\laravel-vouchers\src\Models\Voucher.php_

Code i used to redeem voucher as below..
`$user->redeem($voucherCode);`

It doesn't happen when we put with attributes of '**allow_models**' by providing models of users.
So is it possible to allow any user model.. coz I hv thousands of users that I don't want to include while making voucher.

**Comment by ilyaskazi** [comment]
any update on this?

**Comment by augustusnaz** [comment]
Hey mate, I'm unable to reproduce this issue. Can I see more of ur code? What version of the package are u using?
I suspect that in your case, a null value is returned for `can_redeem` before the foreach() loop at line #340.

Also if u can also share the function code block for `getAllowedUsersArrayAttribute` in ur file vendor\moirei\laravel-vouchers\src\Models\Voucher.php.

**Comment by ilyaskazi** [comment]
Yes I was using a low version. I took update and seems to be fine now.

The bug was here: https://github.com/augustusnaz/laravel-vouchers/commit/444342d1d7e57e8c07741ce540cfe46bd952252b#diff-5821a6765959f67dca3fdb1dc8fda6bf
It is fixed now.. so am closing. Thanks for your input.
